### ISSUE TITLE
Cannot read property 'number' of undefined

### ISSUE THREAD

**Issue by mustafaskir** [fengshanjian/react-native-komect-uikit#1]
no components works ,
each component give an issue and not working
```
Cannot read property 'number' of undefined
Module AppRegistry is not a registered callable module (calling runApplication)
``` 
`Cannot read property 'number' of undefined`
![aa](https://user-images.githubusercontent.com/15132084/36074422-d5235788-0ee3-11e8-9da1-b47d53fa5f72.jpg)

**Comment by developBigXY** [comment]
+1

**Comment by developBigXY** [comment]
import the api used 
![image](https://user-images.githubusercontent.com/30647958/37264007-08c557e4-25e6-11e8-9b80-15da3ee5eaea.png)

**Comment by fengshanjian** [comment]
just close this project , if you like this project, you can see https://github.com/react-native-training/react-native-elements   and  https://github.com/rilyu/teaset  for more help
